--MANEJO DE TRANSACCIONES
USE BD_G5_TALLER_CONTACTABILIDAD
BEGIN TRANSACTION
	INSERT INTO tb_Producto 
	(nombreProducto, cantidadProducto, estadoProducto)
	SELECT 'producto32', '100',1
--COMMIT;
ROLLBACK;
--manejo de errores con try catch
--SECCIÓN 1
BEGIN TRY
	BEGIN TRANSACTION
		INSERT INTO tb_Producto 
		(cantidadProducto, estadoProducto)
		SELECT '100',1
	COMMIT TRANSACTION;
END TRY
--SECCIÓN 2
BEGIN CATCH	
	PRINT 'Salió un error al insertar';
END CATCH


BEGIN TRY
	BEGIN TRANSACTION
		INSERT INTO tb_Producto (nombreProducto, cantidadProducto, estadoProducto)
		SELECT 'producto33', '100',1
		INSERT INTO tb_Producto (nombreProducto, cantidadProducto, estadoProducto)
		SELECT 'producto34', '100',1
		INSERT INTO tb_Producto (cantidadProducto, estadoProducto)
		SELECT '100',1
	COMMIT TRANSACTION;
END TRY
--SECCIÓN 2
BEGIN CATCH	
	ROLLBACK
	PRINT 'Salió un error al insertar';
END CATCH

--USO DEL XACT_ABORT
CREATE TABLE t1  
    (a INT NOT NULL PRIMARY KEY);  
CREATE TABLE t2  
    (a INT NOT NULL REFERENCES t1(a));  
GO 
INSERT INTO t1 VALUES (1);
INSERT INTO t1 VALUES (3);
INSERT INTO t1 VALUES (4);
INSERT INTO t1 VALUES (6);
GO
select * from t1
GO
SET XACT_ABORT OFF;
GO
BEGIN TRANSACTION;
INSERT INTO t2 VALUES (1);
INSERT INTO t2 VALUES (2);
INSERT INTO t2 VALUES (3);
COMMIT TRANSACTION
select * from t2
--truncate table t2
GO
SET XACT_ABORT ON;
GO
BEGIN TRANSACTION;
INSERT INTO t2 VALUES (4);
INSERT INTO t2 VALUES (5);
INSERT INTO t2 VALUES (6);
COMMIT TRANSACTION
select * from t2

BEGIN TRY
	BEGIN TRANSACTION;
		INSERT INTO t2 VALUES (4);
		INSERT INTO t2 VALUES (5);
		INSERT INTO t2 VALUES (6);
	COMMIT TRANSACTION
END TRY
BEGIN CATCH
	SELECT
	ERROR_NUMBER() AS ERRNUM,
	ERROR_MESSAGE() AS ERRMSG,
	ERROR_SEVERITY() AS ERRSEV,
	ERROR_PROCEDURE() AS ERRPROC,
	ERROR_LINE() AS ERRLINE,
	ERROR_STATE() AS ESTADO;
END CATCH